server:
  port: 8080

spring:
  port: 8080
  sql.init.mode: always
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      default_schema: public

    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:changelog/changelog-master.yaml
    default-schema: public

  kafka:
#    bootstrap-servers: "kafka:9092"
#    bootstrap-servers: kafka:9092
    bootstrap-servers: "192.168.1.100:9092,192.168.1.101:9092"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
