version: '3.8'
services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
      - liquibase
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  service-db:
    image: postgres:14.7-alpine
    container_name: service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  liquibase:
    image: liquibase/liquibase:latest-alpine
    container_name: liquibase
    depends_on:
      - service-db
    command: --url=jdbc:postgresql://service-db:5432/postgres?user=postgres&password=postgres --changeLogFile=/db/changelog/changelog-master.yaml update
    volumes:
      - ./db/changelog/changelog-master.yaml:/db/changelog/changelog-master.yaml

volumes:
  db-data:
  pgadmin-data:
