create TABLE IF NOT EXISTS accounts (

      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      account_number UUID UNIQUE NOT NULL,
      customers_id integer references customers(id),
      balance VARCHAR(255),
      currency VARCHAR(255) NOT NULL,
      status VARCHAR(255) NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);