create TABLE IF NOT EXISTS payment_transaction (

      payment_transaction_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      payment_transaction_number UUID UNIQUE NOT NULL,
      ammount VARCHAR(255) NOT NULL,
      currency VARCHAR(255) NOT NULL,
      status VARCHAR(255) NOT NULL,
      errorMessage VARCHAR(255),
      created_at TIMESTAMP NOT NULL,
      executet_at TIMESTAMP
);