create TABLE IF NOT EXISTS payment_transaction (

      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tx_number UUID UNIQUE NOT NULL,
      amount VARCHAR(255) NOT NULL,
      currency VARCHAR(255) NOT NULL,
      status VARCHAR(255) NOT NULL,
      errorMessage VARCHAR(255),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      executet_at TIMESTAMP
);