CREATE TABLE IF NOT EXISTS payment_transactions_refund (

      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      transaction_refund_number UUID UNIQUE NOT NULL,
      payment_transactions_id integer references payment_transactions(id),
      refunded_amount VARCHAR(255) NOT NULL,
      currency VARCHAR(255) NOT NULL,
      status VARCHAR(255) NOT NULL,
      reason VARCHAR(255),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      executet_at TIMESTAMP
);