create TABLE IF NOT EXISTS customers (

      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      customer_number UUID UNIQUE NOT NULL,
      first_name VARCHAR(255) NOT NULL,
      last_name VARCHAR(255) NOT NULL,
      country VARCHAR(255),
      status VARCHAR(255) NOT NULL,
      phone VARCHAR(255) UNIQUE NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);