create TABLE IF NOT EXISTS account (

      account_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      customer_id UUID UNIQUE NOT NULL,
      account_number UUID UNIQUE NOT NULL,
      balance VARCHAR(255) NOT NULL,
      currency VARCHAR(255) NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);