create TABLE IF NOT EXISTS payment_transactions (

      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      transaction_number UUID UNIQUE NOT NULL,
      amount VARCHAR(255) NOT NULL,
      currency VARCHAR(255) NOT NULL,
      status VARCHAR(255) NOT NULL,
      error_message VARCHAR(255),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      executet_at TIMESTAMP
);